test_prompts = [
    {"prompt": "What is the capital of France?", "attractor": "qa"},
    {"prompt": "What is 2+2?", "attractor": "qa"},
    {"prompt": "What color is the sky on a clear day?", "attractor": "qa"},
    {"prompt": "How many legs does a cat have?", "attractor": "qa"},
    {"prompt": "What is the largest planet in our solar system?", "attractor": "qa"},
    {"prompt": "What is the chemical symbol for water?", "attractor": "qa"},
    {"prompt": "Who wrote 'Romeo and Juliet'?", "attractor": "qa"},
    {"prompt": "What is the square root of 16?", "attractor": "qa"},
    {"prompt": "In which year did the Titanic sink?", "attractor": "qa"},
    {"prompt": "What is the tallest mountain on Earth?", "attractor": "qa"},
    {"prompt": "Translate 'hello' into French.", "attractor": "qa"},
    {"prompt": "What is the opposite of 'hot'?", "attractor": "qa"},
    {"prompt": "What is the capital of Italy?", "attractor": "qa"},
    {"prompt": "What is 5*3?", "attractor": "qa"},
    {"prompt": "Name a primary color.", "attractor": "qa"},
    {"prompt": "What is the boiling point of water in Celsius?", "attractor": "qa"},
    {"prompt": "What is the currency of Japan?", "attractor": "qa"},
    {"prompt": "How many continents are there?", "attractor": "qa"},
    {"prompt": "What is the largest mammal?", "attractor": "qa"},
    {"prompt": "What is the past tense of 'go'?", "attractor": "qa"},
]
